march:
  controller:
    joint_state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    temperature_sensor:
      type: march_temperature_sensor_controller/MarchTemperatureSensorController
      publish_rate: 50
    pdb_state:
      type: march_pdb_state_controller/MarchPdbStateController
      publish_rate: 50
    trajectory:
        type: position_controllers/JointTrajectoryController
        # When you switch to effort actuationmode, 'position_controllers' must be substituted with 'effort_controllers' and the gains must be added
        joints:
          - test_joint
#      gains: # Required because we're controlling an effort interface
#        test_joint: {p: 50, i: 0, d: 10, i_clamp: 10, publish_state: true, antiwindup: true}
        # Note: these gains are tuned for the KFE joints in the exoskeleton
