march:
  controller:
    pdb_state:
      type: march_pdb_state_controller/MarchPdbStateController
      publish_rate: 50
    joint_state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    temperature_sensor:
      type: march_temperature_sensor_controller/MarchTemperatureSensorController
      publish_rate: 1
    trajectory:
      type: effort_controllers/JointTrajectoryController
      allow_partial_joints_goal: true
      # When you switch to effort actuationmode, 'position_controllers' must be substituted with 'effort_controllers' and the gains must be added
      joints:
        - left_ankle
        - left_hip_aa
        - left_hip_fe
        - left_knee
        - right_ankle
        - right_hip_aa
        - right_hip_fe
        - right_knee
      gains: # Required because we're controlling an effort interface
        left_ankle: {p: 0, i: 0, d: 0, i_clamp: 100, publish_state: true, antiwindup: true}
        left_hip_aa: {p: 0, i: 0, d: 0, i_clamp: 100, publish_state: true, antiwindup: true}
        left_hip_fe: {p: 0, i: 0, d: 0, i_clamp: 100, publish_state: true, antiwindup: true}
        left_knee: {p: 0, i: 0, d: 0, i_clamp: 100, publish_state: true, antiwindup: true}
        right_ankle: {p: 0, i: 0, d: 0, i_clamp: 100, publish_state: true, antiwindup: true}
        right_hip_aa: {p: 0, i: 0, d: 0, i_clamp: 100, publish_state: true, antiwindup: true} # TODO(BaCo) tune HAA joints
        right_hip_fe: {p: 0, i: 0, d: 0, i_clamp: 100, publish_state: true, antiwindup: true}
        right_knee: {p: 0, i: 0, d: 0, i_clamp: 100, publish_state: true, antiwindup: true}

      constraints:
        left_ankle:
          trajectory: 0.305
          goal: 0.305
        left_hip_aa:
          trajectory: 0.305
          goal: 0.305
        left_hip_fe:
          trajectory: 0.305
          goal: 0.305
        left_knee:
          trajectory: 0.305
          goal: 0.305
        right_ankle:
          trajectory: 0.305
          goal: 0.305
        right_hip_aa:
          trajectory: 0.305
          goal: 0.305
        right_hip_fe:
          trajectory: 0.305
          goal: 0.305
        right_knee:
          trajectory: 0.305
          goal: 0.305
