gait_types:
  sit_like:
    left_ankle: {p: 160, i: 0, d: 6}
    left_hip_aa: {p: 330, i: 0, d: 10}
    left_hip_fe: {p: 60, i: 0, d: 5}
    left_knee: {p: 60, i: 0, d: 10}
    right_ankle: {p: 130, i: 0, d: 6}
    right_hip_aa: {p: 330, i: 0, d: 10}
    right_hip_fe: {p: 60, i: 0, d: 5}
    right_knee: {p: 60, i: 0, d: 10}
  walk_like:
    left_ankle: {p: 160, i: 0, d: 6}
    left_hip_aa: {p: 330, i: 0, d: 10}
    left_hip_fe: {p: 60, i: 0, d: 5}
    left_knee: {p: 60, i: 0, d: 10}
    right_ankle: {p: 130, i: 0, d: 6}
    right_hip_aa: {p: 330, i: 0, d: 10}
    right_hip_fe: {p: 60, i: 0, d: 5}
    right_knee: {p: 60, i: 0, d: 10}
  stairs_like:
    left_ankle: {p: 160, i: 0, d: 6}
    left_hip_aa: {p: 330, i: 0, d: 10}
    left_hip_fe: {p: 60, i: 0, d: 5}
    left_knee: {p: 60, i: 0, d: 10}
    right_ankle: {p: 130, i: 0, d: 6}
    right_hip_aa: {p: 330, i: 0, d: 10}
    right_hip_fe: {p: 60, i: 0, d: 5}
    right_knee: {p: 60, i: 0, d: 10}